language: php
php:
  - 7.0
  - 7.1

services:
  - memcached

before_script:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit -c tests/unit/phpunit.xml